# Generated by Django 4.1.2 on 2022-10-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='markdownFile',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('dataContent', models.TextField()),
            ],
        ),
    ]
