# Generated by Django 4.1.2 on 2022-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
