# Generated by Django 4.1.2 on 2022-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listItems', '0002_alter_markdownfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
